# coding: utf-8
require 'rubygems'
require 'rails'
require 'haml'
require 'active_support'
require 'action_pack'
require 'action_view'
require 'action_controller'
require 'action_view/template'
require 'action_view/test_case'
require 'jquery_ui_rails_helpers/tabs_helper'
